name: Generate TV JSON

on:
workflow_dispatch:
schedule:
- cron: "*/30 * * * *"

jobs:
build:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Install Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"

  - name: Install unzip
    run: sudo apt-get update && sudo apt-get install -y unzip

  - name: Extract ZIP
    run: |
      mkdir extracted
      unzip -P "${{ secrets.ZIP_PASSWORD }}" fifa.zip -d extracted

  - name: Install requirements
    run: |
      pip install requests

  - name: Generate tv.json
    run: |
      python extracted/main.py > tv.json

  - name: Commit tv.json
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      git add tv.json

      git diff --staged --quiet || (
        git commit -m "Update tv.json"
        git push
      )